name: rubocop
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # Use latest version of action
        with:
          ruby-version: '3.2.2'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
